# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_pwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='About Pwares', max_length=200)),
                ('abouthistory', models.TextField()),
                ('titlea', models.CharField(max_length=200)),
                ('descriptiona', models.TextField()),
                ('titleb', models.CharField(max_length=200)),
                ('descriptionb', models.TextField()),
                ('titlec', models.CharField(max_length=200)),
                ('descriptionc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Contact Info', max_length=200)),
                ('about_ourcontacts', models.TextField()),
                ('email_address', models.CharField(max_length=200)),
                ('phone_numbera', models.CharField(max_length=200)),
                ('phone_numberb', models.CharField(max_length=200)),
                ('linkedin_link', models.CharField(max_length=200)),
                ('google_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
                ('current_year', models.CharField(default='2018', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Portfolio', max_length=200)),
                ('portfoliohistory', models.TextField()),
                ('photo', models.FileField(upload_to='portfolio/')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Ratings', max_length=200)),
                ('creativedesign', models.CharField(default='1', max_length=200)),
                ('happyclients', models.CharField(default='1', max_length=200)),
                ('peopleloved', models.CharField(default='1', max_length=200)),
                ('saveincome', models.CharField(default='1', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Services', max_length=200)),
                ('servicehistory', models.TextField()),
                ('serviceone', models.CharField(max_length=200)),
                ('serviceone_info', models.TextField()),
                ('servicetwo', models.CharField(max_length=200)),
                ('servicetwo_info', models.TextField()),
                ('servicethree', models.CharField(max_length=200)),
                ('servicethree_info', models.TextField()),
                ('servicefour', models.CharField(max_length=200)),
                ('servicefour_info', models.TextField()),
                ('servicefive', models.CharField(max_length=200)),
                ('servicefive_info', models.TextField()),
                ('servicesix', models.CharField(max_length=200)),
                ('servicesix_info', models.TextField()),
                ('serviceseven', models.CharField(max_length=200)),
                ('serviceseven_info', models.TextField()),
                ('serviceeight', models.CharField(max_length=200)),
                ('serviceeight_info', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Testimonials', max_length=200)),
                ('clientname', models.CharField(max_length=200)),
                ('clienttitle', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='testimonials/')),
                ('clienttext', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pwares_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pwares Updates', max_length=200)),
                ('about_updates', models.TextField()),
                ('photo', models.FileField(upload_to='siteupdates/')),
                ('update_title', models.CharField(max_length=200)),
                ('update_source', models.CharField(max_length=200)),
                ('update_info', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
